title:          Title of your project
description:    It's a ouaaaouhh project !
lang :          en

gitlabURL:      www.urlgitlab.com

# chemin d'analyse
srcPath : /home/jd/html/Redis/src

# métrique quantitative
count : true
 
# métrique qualité copy-paste
cpd : true

# métrique qualité code sniffer
cs :
    enable: true
    standard: PSR2

# métrique qualité php depend
depend : true

# métrique qualité php loc
loc : true

# métrique qualité mess detector
md :
    enable: true
    rules: 
        cleancode: false
        codesize: true
        controversial: true  
        design: true  
        naming: true
        unusedcode: true

# possiblité de généré la phpdoc 
docs : true

# tests unitaires et fonctionnels
test :
    enable: true
    lib : atoum       # phpunit || atoum
    phpunitTestSuite : 
    atoumPath : /home/jd/html/Redis/vendor/bin/atoum
    atoumTestDir : /home/jd/html/Redis/tests

# score
score:
    enable:         true
    csWeight:       100     # between 0 and 100, weighting of code sniffer
    testWeight:     100     # between 0 and 100, weighting of testing
    locWeight:      100     # between 0 and 100, weighting of code coverage
    projectSize:    medium  # small : betwenn 0 and 5000, medium, between 5000 and 50000, big : > 50000

# historisation
histo:
    enable : true
    jsonPretty : true
