title: Ges'Mouv
description: Application web sur mobile pour commerciaux FOS

gitlabURL: http://lxlyocvs12:9292/fos-mobilite-web/

# chemin d'analyse
srcPath : /home/FIDUCIAL/adm_jd.labails/fos/src
paPath : /home/FIDUCIAL/adm_jd.labails/fos/web/pa

# métrique quantitative
count : true

# métrique qualité copy-paste
cpd : true

# métrique qualité code sniffer 
cs :
    enable: true
    standard: PSR1

# métrique qualité php depend
depend : false

# métrique qualité php loc
loc : true

# métrique qualité mess detector
md :
    enable: true
    rules:
        codeclean: false
        codesize: true
        controversial: true
        design: true
        naming: true
        unusedcode: true

# possiblité de généré la phpdoc
docs : true

# tests unitaires et fonctionnels
test :
    enable: false
    lib : phpunit
    testsuite : GesMouv
